### ISSUE TITLE
Export Delivery.key

### ISSUE THREAD

**Issue by foxcpp** [emersion/go-maildir#1]
It would be useful to be able to get key that will be used for a new message.

https://github.com/emersion/go-maildir/blob/7f0723ff42deca6c63fb012999c506745d161df8/maildir.go#L286

**Comment by emersion** [comment]
What is the usee-case?

**Comment by foxcpp** [comment]
foxcpp/go-imap-sql#1. Add delivered message to database.

**Comment by emersion** [comment]
Hmm. `Delivery` is supposed to be used if you are delivering to another process. If you're delivering internally you shouldn't need to use it?

**Comment by foxcpp** [comment]
If I will write directly to `cur` directory, any other process working with Maildir may see partially written (thus corrupted) message. The whole point of Maildir use in go-imap-sql is to make that interoperability possible. Even though I now doubt the whole idea of maildir in go-imap-sql (it seems to add more complexity than necessary to get the job done), issue raised here is more general: any maildir-compatible application that may want to have some sort of index will need to get that key.

**Comment by emersion** [comment]
Maildir is designed to allow multiple processes to deliver to a directory, and one process to receive messages. It is not designed for multiple processes to read from `cur`.

If you deliver a message, you give it to a foreign process, thus you shouldn't store the key anywhere. You don't know (and you shouldn't care) if and when the message will be delivered (moved from `tmp` to `cur`).

**Comment by foxcpp** [comment]
Eh, okay, I guess I will just dump messages into `cur` directly.

**Comment by emersion** [comment]
Oh, and for reference here's why it isn't safe for multiple processes to access `cur`.

1. Process 1 begins to read messages from `cur`, one by one. Each `readdir` call returns a filename (which go-maildir calls keys) and metadata is extracted from those.
2. Process 2 changes a message's flag. This renames a filename process 1 has already read to another one.
3. Process 1 continues to read, `readdir` returns the new filename and it's counted twice.

Of course this isn't the only race.
