### ISSUE TITLE
Problems with folders with square brackets?

### ISSUE THREAD

**Issue by 097115** [emersion/go-maildir#10]
Hi!

Sorry to disturb you (and I may be very well wrong) but `go-maildir` seems to have some problems if copying or moving messages to folders with names containing `[` and `]` symbols, like `[test]` (names like `(test)`, on the other hand, work just fine).

The problem, precisely, results in the separator, `:`, disappearing in the process. Like this:

1. Let's say, I have `maildir/saved/cur` folder with `1604807057.kad.1017310000b9e03f0de0e29b35372c:2,` message in it
2. I launch `aerc`, enter the folder, and with the cursor being on that message, issue the command `:cp [test]`
3. `go-maildir`'s `newKey()` then generates the new key, something like: `1604837003.kad.1693510001d15771d757276d40aadz`
4. with that key, `go-maildir`'s `filenameGuesses()` produces the correct basename: `maildir/[test]/cur/1604837003.kad.1693510001d15771d757276d40aadz:2,`
5. And then, `aerc`'s function `handleCopyMessages()` from `worker/maildir/worker.go` returns the following error (so, I'm not exactly sure if it's on your side, or on theirs):

        %!(EXTRA *errors.errorString=could not copy message 51: maildir: key 1604837003.kad.1693510001d15771d757276d40aadz matches 0 files., string=
        )

And if I inspect this `maildir/[test]/cur` folder manually, then I see the following file with no separator there:

    maildir/[test]/cur> dir
    total 4.0K
    -rw------- 1 s 3.2K Nov  8 14:03 1604837003.kad.1693510001d15771d757276d40aadz2,

(For the record, I tried changing `:` to `!`, for example, but the problem doesn't go away :). Happens both on Linux and macOS.)

Would be grateful for some advise may be :)

Thank you!

**Comment by emersion** [comment]
Does it fix your issue if you add `separator` to this line

https://github.com/emersion/go-maildir/blob/ced1977bfb902354b2a8bfbf7517b8d6ba07cccb/maildir.go#L382

Like this:

```go
curfile := filepath.Join(string(target), "cur", targetKey+string(separator)+"2,")
```

**Comment by 097115** [comment]
@emersion Indeed it works! Thank you very much :)

**Comment by emersion** [comment]
Can you submit a pull request?

**Comment by 097115** [comment]
I'm not a programmer, have no experience with that. Can take some time :)

**Comment by emersion** [comment]
Re-opening since this bug is still not fixed.
