### ISSUE TITLE
Errors in messages prevent opening

### ISSUE THREAD

**Issue by agenbite** [emersion/go-maildir#12]
Hi! I just wanted to confirm that it is a design decission to prevent opening messages that have some sort of trouble. I'm getting errors like the following:

`could not get message info: could not get structure: could not parse content type: mime: invalid media parameter`
`could not get message info: could not get structure: multipart: NextPart: EOF`
`could not get message info: could not get structure: could not parse content type: mime: unexpected content after media subtype`
`could not get message info: could not get structure: could not parse content type: mime: invalid media parameter`
`could not get message info: could not get structure: could not parse child entity structure: could not parse content disposition: mime: no media type`
`could not get message info: could not get structure: could not parse child entity structure: could not parse content type: mime: expected slash after first token`

From what I've seen, the messages involved do have certains irregularities, but they're open with no complains by other softwares.

In any case, thanks for this library!

**Comment by emersion** [comment]
These errors don't come from go-maildir.
