### ISSUE TITLE
failing to parse filenames with more than one colon

### ISSUE THREAD

**Issue by ferdinandyb** [emersion/go-maildir#23]
go-maildir chokes on filenames like `1686325684.2046813_1.mashenka,U=103:2:2,RS` On aerc-devel the conclusion was that this is actually valid maildir (see [discussion](https://lists.sr.ht/~rjarry/aerc-devel/%3CCY9A00KH5C1Z.26PY7P1UCTWZP%40ferdinandy.com%3E) and [ticket](https://todo.sr.ht/~rjarry/aerc/215).

On a side-note, I haven't tested very thoroughly, but I had the feeling that if there _is_ an error found in the folder not all of the valid files are returned, but I'm not completely certain.

**Comment by emersion** [comment]
This doesn't look like a valid maildir filename to me. The "info" section is "2,RS", but there is an extra ":" character before.

**Comment by ferdinandyb** [comment]
Hmm, we were thinking about it as uniq being up to the first `:2`. On the other hand, I checked what isync records as uniq and indeed it only seems to store the number, not `103:2`, so you're probably right.

**Comment by emersion** [comment]
"2:2,RS" is not a valid info field. The info field starts with a version number and is followed by a comma.

**Comment by ferdinandyb** [comment]
Ok, sorry for the noise and thanks for your time!

**Comment by emersion** [comment]
FWIW, I still think we could improve go-maildir to better support invalid files. We could accumulate filename errors in `Walk`, and return them at the end.

**Comment by ferdinandyb** [comment]
That would be great.  Aerc then could push a file count in the error message and log the bad paths.

**Comment by emersion** [comment]
Would you be willing to send a patch for this?

**Comment by ferdinandyb** [comment]
Sure, it doesn't seem very complicated. Should I do a PR here or can I send a patch somewhere?

**Comment by emersion** [comment]
You can either send a pull request or send a patch to my public inbox.

I'd suggest using `errors.Join` since we may hit multiple non-fatal errors along the way. I think if the callback passed to `Walk` returns an error we'd still want to immediately stop.
