### ISSUE TITLE
Better way to get the `key` of a delivered message

### ISSUE THREAD

**Issue by gjabell** [emersion/go-maildir#4]
As mentioned in #1, there is currently no easy way to get the `key` value of a message added to the store using a `Delivery` (the best option at the moment seems to be using the `Keys` method to get a list of keys, which then have to be checked against the original key list to determine which keys are new).

Exposing the `key` value would allow the "single receiving and reading process" to deliver a message and then perform modifications on the delivered message without having to keep track of existing keys.

**Comment by emersion** [comment]
Maildir assumes one process managing the dir and multiple processes writing to it. `Delivery` is meant for write-only processes. `Delivery` appends the new mail to the `new` subdirectory, and these new messages should be handled by the process managing the maildir (by moving them to the `cur` subdirectory).

There are two things we could do:

1. Make the split more obvious. Make it so `NewDelivery` isn't a `Dir` method, but instead a top-level function. This would allow the docs to say that `Dir` must only be used by processes managing the maildir.
2. Add a way for processes managing the maildir to append messages directly in the `cur` subdirectory.

**Comment by emersion** [comment]
@gjabell, can you confirm the new function suits your needs? https://godoc.org/github.com/emersion/go-maildir#Dir.Create

**Comment by gjabell** [comment]
@emersion that seems to work great, I'm testing an `aerc` patch now and I'll send it in for comments soon :) Thanks for your work!
